### ISSUE TITLE
Internal error when moving cursor by pen and mouse simultaneously

### ISSUE THREAD

**Issue by loentar** [mypaint/mypaint#460]
I saw this error thousand times, but was not able to reproduce it reliably.

Well, if you painting with pen or just positioning it and in the same time you move a mouse the error dialog appear:

![screenshot from 2015-10-24 12 02 20](https://cloud.githubusercontent.com/assets/4038431/10709885/212cf712-7a47-11e5-91f9-7f42fd5e5159.png)

```python
Mypaint version: 1.2.0-beta.1.96+git.0451151
System information: Linux-3.19.0-23-generic-x86_64-with-Ubuntu-15.04-vivid
Traceback (most recent call last):
  File "/usr/local/share/mypaint/gui/document.py", line 627, motion_notify_cb(self=<gui.document.Document object>, tdw=<TiledDrawWidget object at 0x7f98d0b3ec30 (TiledDrawWidget at 0x27d5850)>, event=<void>)
            # Normal event dispatch
            CanvasController.motion_notify_cb(self, tdw, event)
            return False  # XXX don't consume motions to allow workspace autohide
  variables: {'CanvasController.motion_notify_cb': ('global', <unbound method CanvasController.motion_notify_cb>), 'self': ('local', <gui.document.Document object at 0x7f98d0b4ef10>), 'tdw': ('local', <TiledDrawWidget object at 0x7f98d0b3ec30 (TiledDrawWidget at 0x27d5850)>), 'event': ('local', <void at 0x215eb4c0>)}
  File "/usr/local/share/mypaint/gui/document.py", line 119, motion_notify_cb(self=<gui.document.Document object>, tdw=<TiledDrawWidget object at 0x7f98d0b3ec30 (TiledDrawWidget at 0x27d5850)>, event=<void>)
            mode = self.modes.top
            result = mode.motion_notify_cb(tdw, event)
            self._update_last_event_info(tdw, event)
  variables: {'mode.motion_notify_cb': ('local', <bound method FreehandMode.motion_notify_cb of <gui.freehand.FreehandMode object at 0x7f98b396a450>>), 'tdw': ('local', <TiledDrawWidget object at 0x7f98d0b3ec30 (TiledDrawWidget at 0x27d5850)>), 'result': (None, []), 'event': ('local', <void at 0x215eb4c0>)}
  File "/usr/local/share/mypaint/gui/freehand.py", line 537, motion_notify_cb(self=<gui.freehand.FreehandMode object>, tdw=<TiledDrawWidget object at 0x7f98d0b3ec30 (TiledDrawWidget at 0x27d5850)>, event=<void>, fakepressure=None)
                    tilt_angle = math.atan2(ytilt, xtilt) - tdw.rotation
                    tilt_magnitude = math.sqrt((xtilt**2) + (ytilt**2))
                    xtilt = tilt_magnitude * math.cos(tilt_angle)
  variables: {'xtilt': ('local', -1.63e-322), 'ytilt': ('local', 6.077204211587006e+247), 'math.sqrt': ('global', <built-in function sqrt>), 'tilt_magnitude': (None, [])}
OverflowError: (34, 'Numerical result out of range')
```

**Comment by loentar** [comment]
Also it's reproduced only when canvas is rotated

**Comment by achadwick** [comment]
I can't reproduce this with a touchscreen and a trackpad together, but then again neither of them have tilt :/ I'll have to wait before I get to a machine with a graphics tablet before I can debug this.

**Comment by achadwick** [comment]
Cannot reproduce this with a touchpad/tablet combo. But maybe like #344 it needs an actual physical mouse.

I thought this was fixed in fe1a0877e1a6ac06704ec724d4506d3b0a0339fe too :disappointed: 

@loentar Is this still happening with MyPaint v1.2.0-beta.2 ? Please upgrade and test.

Also, does the commit above help with this if it's still happening in the latest beta? You will have to build MyPaint in order to test it out since it's newer than the latest beta.

**Comment by achadwick** [comment]
Glad I remembered #344. This one does need a physical mouse to reproduce!

But yes - this is reproducible in v1.2.0-beta.2 with tablet in one hand and mouse in the other, and only with the canvas rotated as reported. Thanks, @loentar !

I believe it is fixed (or at least worked around) by fe1a0877e1a6ac06704ec724d4506d3b0a0339fe. Please test if you can, but I'm considering this one closed for now.

**Comment by loentar** [comment]
It's still reproducible from current (clean) master:

```python
Mypaint version: 1.2.0-beta.2.15+git.ab2bb78
System information: Linux-3.19.0-23-generic-x86_64-with-Ubuntu-15.04-vivid
Traceback (most recent call last):
  File "/home/dem/devel/mypaint/gui/document.py", line 628, motion_notify_cb(self=<gui.document.Document object>, tdw=<TiledDrawWidget object at 0x7fa8bd0d2aa0 (TiledDrawWidget at 0x1f7a850)>, event=<void>)
            # Normal event dispatch
            CanvasController.motion_notify_cb(self, tdw, event)
            return False  # XXX don't consume motions to allow workspace autohide
  variables: {'CanvasController.motion_notify_cb': ('global', <unbound method CanvasController.motion_notify_cb>), 'self': ('local', <gui.document.Document object at 0x7fa8bde24350>), 'tdw': ('local', <TiledDrawWidget object at 0x7fa8bd0d2aa0 (TiledDrawWidget at 0x1f7a850)>), 'event': ('local', <void at 0x4d1b420>)}
  File "/home/dem/devel/mypaint/gui/document.py", line 119, motion_notify_cb(self=<gui.document.Document object>, tdw=<TiledDrawWidget object at 0x7fa8bd0d2aa0 (TiledDrawWidget at 0x1f7a850)>, event=<void>)
            mode = self.modes.top
            result = mode.motion_notify_cb(tdw, event)
            self._update_last_event_info(tdw, event)
  variables: {'mode.motion_notify_cb': ('local', <bound method FreehandMode.motion_notify_cb of <gui.freehand.FreehandMode object at 0x7fa8b46eb5d0>>), 'tdw': ('local', <TiledDrawWidget object at 0x7fa8bd0d2aa0 (TiledDrawWidget at 0x1f7a850)>), 'result': (None, []), 'event': ('local', <void at 0x4d1b420>)}
  File "/home/dem/devel/mypaint/gui/freehand.py", line 556, motion_notify_cb(self=<gui.freehand.FreehandMode object>, tdw=<TiledDrawWidget object at 0x7fa8bd0d2aa0 (TiledDrawWidget at 0x1f7a850)>, event=<void>, fakepressure=None)
                    tilt_angle = math.atan2(ytilt, xtilt) - tdw.rotation
                    tilt_magnitude = math.sqrt((xtilt**2) + (ytilt**2))
                    xtilt = tilt_magnitude * math.cos(tilt_angle)
  variables: {'xtilt': ('local', 1.63e-322), 'ytilt': ('local', 2.7810664958391754e+180), 'math.sqrt': ('global', <built-in function sqrt>), 'tilt_magnitude': (None, [])}
OverflowError: (34, 'Numerical result out of range')
```

The second value `2.7810664958391754e+180 ** 2` causes the error.

**Comment by loentar** [comment]
If I add 

```print("xtilt=" + str(xtilt) + " ytilt=" + str(ytilt))```

before 

```if xtilt is None or ytilt is None or not isfinite(xtilt+ytilt):```

I see the values in terminal:


```
xtilt=2.42092166462e-322 ytilt=2.92925711207e-316
xtilt=0.00787401574803 ytilt=0.00787401574803
xtilt=None ytilt=None
xtilt=1.63041663128e-322 ytilt=9.08796752178e+227
Traceback (most recent call last):
  File "/home/dem/devel/mypaint/gui/document.py", line 628, in motion_notify_cb
    CanvasController.motion_notify_cb(self, tdw, event)
  File "/home/dem/devel/mypaint/gui/document.py", line 119, in motion_notify_cb
    result = mode.motion_notify_cb(tdw, event)
  File "/home/dem/devel/mypaint/gui/freehand.py", line 557, in motion_notify_cb
    tilt_magnitude = math.sqrt((xtilt**2) + (ytilt**2))
OverflowError: (34, 'Numerical result out of range')
xtilt=0.00787401574803 ytilt=0.00787401574803
xtilt=None ytilt=None
xtilt=2.42092166462e-322 ytilt=2.9292535548e-316
xtilt=0.00787401574803 ytilt=0.00787401574803
xtilt=None ytilt=None
xtilt=2.42092166462e-322 ytilt=2.45290866029e-316
xtilt=0.00787401574803 ytilt=0.00787401574803
xtilt=None ytilt=None
xtilt=1.52616878e-320 ytilt=1.22630871222e+194
Traceback (most recent call last):
  File "/home/dem/devel/mypaint/gui/document.py", line 628, in motion_notify_cb
    CanvasController.motion_notify_cb(self, tdw, event)
  File "/home/dem/devel/mypaint/gui/document.py", line 119, in motion_notify_cb
    result = mode.motion_notify_cb(tdw, event)
  File "/home/dem/devel/mypaint/gui/freehand.py", line 557, in motion_notify_cb
    tilt_magnitude = math.sqrt((xtilt**2) + (ytilt**2))
OverflowError: (34, 'Numerical result out of range')
xtilt=0.00787401574803 ytilt=0.00787401574803
xtilt=0.00787401574803 ytilt=0.00787401574803
xtilt=None ytilt=None
xtilt=2.42092166462e-322 ytilt=6.94723852744e-310
xtilt=0.00787401574803 ytilt=0.00787401574803
xtilt=None ytilt=None
xtilt=1.63041663128e-322 ytilt=9.08796752178e+227
Traceback (most recent call last):
  File "/home/dem/devel/mypaint/gui/document.py", line 628, in motion_notify_cb
    CanvasController.motion_notify_cb(self, tdw, event)
  File "/home/dem/devel/mypaint/gui/document.py", line 119, in motion_notify_cb
    result = mode.motion_notify_cb(tdw, event)
  File "/home/dem/devel/mypaint/gui/freehand.py", line 557, in motion_notify_cb
    tilt_magnitude = math.sqrt((xtilt**2) + (ytilt**2))
OverflowError: (34, 'Numerical result out of range')
xtilt=0.00787401574803 ytilt=0.00787401574803
xtilt=None ytilt=None
```


When moving the mouse alone, I see the values:

```
xtilt=None ytilt=None
xtilt=None ytilt=None
xtilt=None ytilt=None
xtilt=None ytilt=None
```


When using pen only the values is always:

```
xtilt=0.00787401574803 ytilt=0.00787401574803
xtilt=0.00787401574803 ytilt=0.00787401574803
xtilt=0.00787401574803 ytilt=0.00787401574803

```

My tablet don't have tilt support.

**Comment by loentar** [comment]
And patch I suggested still fixes the error: https://gist.github.com/loentar/30c375f091967a98575c

**Comment by achadwick** [comment]
Sorry, I didn't see the patch earlier. I'll take another look at that.

**Comment by achadwick** [comment]
@loentar This should be fixed with f8a94b0680726f9086aa813ef5f6c48c10224d3e - can you re-test again please?

**Comment by loentar** [comment]
Yes. I cannot reproduce it anymore, thanks!

**Comment by achadwick** [comment]
Okay, closing with a bit more confidence. Thanks for testing!
