### ISSUE TITLE
Palette window: middle button + drag behaviour looks weird ("lighten/darken" jumps the match cursor around all over the place)

### ISSUE THREAD

**Issue by achadwick** [mypaint/mypaint#63]
Most colour selectors allow you to darken or lighten a chosen colour in HCY space by clicking to select like normal but with the _middle_ mouse button and then dragging up or down with the middle button still held down. When you release the button, you can paint with a darker or lighter shade of a colour immediately.

The palette selector has a different fancy behaviour which doesn't play well with this "luma shifting"* feature. When you change the colour anywhere, the palette moves its cursor around to keep up: it tries to show the closest match, and uses a fainter border for the dashed cursor to indicate more approximate matches.

When you do the middle button trick though, the approximate matching kicks in, and the cursor bounces around all over the place, which looks really weird:

![Animation: weird palette middle-button drag behaviour](https://cloud.githubusercontent.com/assets/61299/3673295/8ba8cfca-126b-11e4-8401-98ae29aec926.gif)

Ideally I'd like the cursor to stay where it is after the initial click, and for the clicked colour cell, ![Inline: colour cell from animation](https://cloud.githubusercontent.com/assets/61299/3673624/adbd4ed0-126e-11e4-8ba7-eb2270ce52a1.gif), to show the luma-shifted colour somehow. That in itself is orthogonal to the idea of a palette where each cell should show the colour in that cell (damnit), so getting the details right here without causing confusion might be tricky.

Minor enhancement, since hardly anyone knows about the luma-shifting feature.

\* I have _literally no idea_ what to call this feature.

**Comment by 0ion9** [comment]
Mm, ok. Guess I need to make a patch to revert that; Ideally it would also set current pencolor = closest palette color, when releasing, I think.

(I don't really get why this is 'weird', since the palette display will also jump around showing the best match as you use other color-selectors to change pen color.)

**Comment by achadwick** [comment]
@0ion9 
Sure, happy to accept any PR that does what you said if it doesn't break the context menu or make the widget behave strangely. Shall I assign this issue to you? I'm hands-off on the palette for a bit now.

IIRC, it came about because at one time in the development, if you popped up the context menu with button-3, the colour tweaking grab was still active: so as you moved the mouse, the color jumped around as described above. This was during development of the related series of palette menu commits though, so this little glitch may have been fixed (\*thinks\*... smarter return values in the handlers and/or not showing the insert marker and the match marker at the same time may make this redundant now).

If you like it and want it back, yell out.

**Comment by 0ion9** [comment]
Oooh, I see, the palette editor context menu, not the main menu.
Yeah, that bug is still currently present, though slightly different: the color doesn't change while menu is up, but only after the menu disappears.  Also shows up in the editor dialog, and worse, is inherited by the main dialog (ie. if you induce the glitch in the editor and don't stop it, it's still in luma-changing mode when you close the editor). Haven't looked at the code yet but I guess any change that unconditionally cancels drag operations after the menu closes would do.

Arguably we should also have a way of disabling the mdrag for the editor dialog, but this is less of a problem because there is no evidence that it is actually occurring (aside from the buggy button release behaviour)

I don't mind taking this on, though of course I can see that for a trunk-worthy solution, I would have to find some way of making what is going on clearer. 

Since you are OP who stated behaviour looks 'weird', what do you think of the idea of a little popup statusbar-thing at bottom of palette dialog saying "A matches B best [Use B]"?
With A and B being color sample panels, A the currently set pen color, and [Use B] being a large button taking up all horizontal space that the text does not.
It could display whenever the pen color is not in the palette.

I considered the possibility of having a "+" button as well, but thought that would make it too easy to add colors by accident.
I also considered using the main statusbar, but that seems weird and also requires excessive travel AFAICS.

**Comment by achadwick** [comment]
Luma-changing mode should be OFF in trunk. Is that with 4ef4eef and only 4ef4eef reverted?

> Since you are OP who stated behaviour looks 'weird', what do you think of the idea of a little popup statusbar-thing at bottom of palette dialog saying "A matches B best [Use B]"?

Sounds like clutter to me. There's already a way of representing approximate matches right there in the weight of the match marker square. Maybe the marker could be made more useful for this case?

The "weirdness" I mentioned referred only to this bouncing-around behaviour on middle button + drag up/down:
![Animation: weird palette middle-button drag behaviour](https://cloud.githubusercontent.com/assets/61299/3673295/8ba8cfca-126b-11e4-8401-98ae29aec926.gif)

As I see it we have two options:

* simplest: remove the feature!
  - not to be dismissed! If the feature is made harder to explain because this is a palette panel, maybe it does't belong on the palette panel.
* better? reinstate it, but don't bounce that match square all over the place _during_ dragging
  - (It'd be ok for the match to move when the button is _released_, now you have a new colour to paint with...)
  - I guess you could show the upcoming brush colour near the cell where the drag started?
  - Obv. you're not changing the colour in the cell itself - it's just a starting point. So that swatch doesn't change.

But I'm not sure about adding extra UI into the palette panel. Something like a GtkPopover maybe? But that's only in GTK 3.12 and we're chasing GTK 3.10...

**Comment by 0ion9** [comment]
>  Is that with 4ef4eef and only 4ef4eef reverted?
It's just with ALLOW_HCY_TWEAK set to True instead of False.

> (It'd be ok for the match to move when the button is released, now you have a new colour to paint with...)

Hm. I'm getting the picture that our expectations do not match (for me, having it jumping around during the change is *actively useful and desirable* -- equivalent to being able to see where I am in the gamut-mask shape of HCY selector.).
I'd be willing to implement calculate-match-only-on-button-release, I guess, if anyone actually would find it useful. I would definitely be locally reverting it, of course.

Not sure what else to say. I'm viewing palettes as a kind of extended-indexed-image facility (IOW what index the current color maps to is pretty important) and you have some other view of it.. 'just colors to start from', maybe? I guess that's the common view, really; and most likely the desire to have a way to easily set pen-color=best palette match is something that fits best into the indexed-color viewpoint.

Well, I can implement the pen-color=best-palette-match thing, anyway, just as a menu item. Anything else could be considered after that (I'd also like a function that sets pen-color=best-palette-match automatically after every color change concludes, but I suspect a) that's rather specialized to my use case and b) working out a good UI is difficult)

**Comment by achadwick** [comment]
@0ion9 Any update on this? I'm closing this issue now since we're getting concrete about the string freeze that begins the 1.2.0-beta cycle, and since the original glitch is fixed to my satisfaction. If you have an implementation of your proposals please submit them as a PR referencing this issue.
